#!/usr/bin/env python3
# Copyright (c) 2025 Kataglyphis
# SPDX-License-Identifier: MIT
"""Every preflight slug needs a proof -- a test suite naming its script, or a
mutation -- and docs/code-quality-gates.md must be the table this derives.
Unproven slugs are frozen in gate-proofs.allow and may only leave it.
docs/code-quality-tooling.md#gate-proof-registry-gate-registry"""
import argparse
import json
import os
import re
import shlex
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from quality_allow import check_keys, load_keys  # noqa: E402
from verify_code_size import scan, shell_functions  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PREFLIGHT = os.path.join(HERE, "preflight.sh")
ALLOW = os.path.join(HERE, "gate-proofs.allow")
TESTS_DIR = os.path.join(HERE, "tests")
MUTATIONS = os.path.join(ROOT, "docs", "scripts", "mutations.json")
HOOK_DIR = os.path.join(ROOT, "linux", "host-config", "git-hooks")
REGISTRY = os.path.join(ROOT, "docs", "code-quality-gates.md")
BY_CONSTRUCTION = ("script-tests", "mutations")
UNPROVEN = "UNPROVEN (frozen)"
EMPTY = "—"
ID_FREEZE = "mutation-id:"
FAMILY = "mutation-family:"

RUN_CHECK = re.compile(r'^\s*run_check\s+([a-z0-9-]+)\s+"([^"]*)"\s*(.*)$')
KNOWN = re.compile(r"KNOWN_SLUGS=\((.*?)\)", re.DOTALL)
FAST = re.compile(r'_FAST_SLUGS="([^"]*)"', re.DOTALL)
GUARD = re.compile(r'^if \[ -n "\$\{(_[A-Za-z0-9_]+)\}" \]; then$')
CHANGED = "--changed"
ALLOW_LIT = re.compile(r"[A-Za-z0-9_./-]+\.allow\b")
IMPORT = re.compile(r"^from\s+([A-Za-z_][A-Za-z0-9_]*)\s+import\b", re.MULTILINE)
SHELLS_OUT = re.compile(r"(?:python3?|bash|sh)\s+([A-Za-z0-9_./-]+\.(?:py|sh))\b")
WORD = re.compile(r"(?<![\w/.-])([A-Za-z_][A-Za-z0-9_]*)(?![\w/.-])")
NEEDLE = r"(?<![\w.-])%s\b"
GENERATED = "<!-- generated by linux/scripts/verify_gate_registry.py --write; do not edit -->"
COLUMNS = ("slug", "preflight name", "script", "allow files", "tests",
           "mutations", "hook tier", "proof")


def _read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def known_slugs(text):
    m = KNOWN.search(text)
    return m.group(1).replace("\\", " ").split() if m else []


def run_checks(text):
    """[(slug, name, tokens, command_text)] for every run_check call, multi-line quoted
    commands included; a slug's `[ -f ] ... MISSING` fallback line is dropped."""
    lines = text.split("\n")
    found = []
    i = 0
    while i < len(lines):
        m = RUN_CHECK.match(lines[i])
        i += 1
        if not m:
            continue
        cmd = m.group(3)
        while True:
            try:
                tokens = shlex.split(cmd)
                break
            except ValueError:
                if i >= len(lines):
                    raise SystemExit("preflight.sh: unterminated run_check command for %s" % m.group(1))
                cmd += "\n" + lines[i]
                i += 1
        found.append((m.group(1), m.group(2), tokens, cmd))
    per_slug = {}
    for entry in found:
        per_slug.setdefault(entry[0], []).append(entry)
    out = []
    for slug, entries in per_slug.items():
        real = [e for e in entries if "MISSING" not in e[3]] if len(entries) > 1 else entries
        if len(real) != 1:
            raise SystemExit("preflight.sh: %d run_check lines for %s, cannot pick one" % (len(real), slug))
        out.append(real[0])
    return out


def shell_defs():
    """name -> [(rel, start_line, line_count)] for every shell function in the tree."""
    defs = {}
    for path, rel in scan(".sh"):
        for _rel, name, start, body in shell_functions(path, rel):
            defs.setdefault(name, []).append((rel, start, len(body)))
    return defs


def resolve_script(tokens, cmd, defs, preflight_rel):
    """(rel, (start, count) or None, needle): the first .py/.sh token that is a repo
    file (needle = its basename), else the file defining the last shell function the
    command names (needle = the function name)."""
    for tok in tokens:
        if tok.endswith((".py", ".sh")) and os.path.isfile(os.path.join(ROOT, tok)):
            return tok, None, os.path.basename(tok)
    for word in reversed(WORD.findall(cmd)):
        if word not in defs:
            continue
        sites = defs[word]
        pick = [s for s in sites if s[0] == preflight_rel] or \
               [s for s in sites if s[0] in cmd] or sorted(sites)
        rel, start, count = pick[0]
        return rel, (start, count), word
    return None, None, None


def script_text(rel, extent):
    text = _read(os.path.join(ROOT, rel))
    if extent is None:
        return text
    start, count = extent
    return "\n".join(text.split("\n")[start - 1:start - 1 + count])


def allow_files(rel, text):
    script_dir = os.path.dirname(os.path.join(ROOT, rel))
    out = set()
    for lit in ALLOW_LIT.findall(text):
        base = os.path.basename(lit)
        for cand in ([os.path.join(ROOT, lit)] if "/" in lit else []) + [
                os.path.join(script_dir, base), os.path.join(ROOT, "docs", "scripts", base)]:
            if os.path.isfile(cand):
                out.add(os.path.relpath(cand, ROOT))
                break
    return sorted(out)


def imported_modules(rel, text):
    if not rel.endswith(".py"):
        return []
    script_dir = os.path.dirname(rel)
    out = []
    for mod in IMPORT.findall(text):
        cand = os.path.join(script_dir, mod + ".py")
        if os.path.isfile(os.path.join(ROOT, cand)):
            out.append(cand)
    return out


def mentions(needle, text):
    return re.search(NEEDLE % re.escape(needle), text) is not None


def mutation_entries():
    return json.loads(_read(MUTATIONS)) if os.path.isfile(MUTATIONS) else []


def id_slug(entry):
    return entry["id"].split(".", 1)[0]


def shelled_out(rel, text):
    """The helpers a .sh gate RUNS as a separate program. A shell gate imports
    nothing, so without this its extractor or sub-gate belongs to no row at all."""
    if not rel.endswith(".sh"):
        return []
    out = set()
    for cand in SHELLS_OUT.findall(text):
        cand = os.path.normpath(cand)
        if cand != rel and os.path.isfile(os.path.join(ROOT, cand)):
            out.add(cand)
    return sorted(out)


def own_files(rel, text):
    return [rel] + imported_modules(rel, text) + shelled_out(rel, text)


def names_suite(entry, tests):
    return any(t in entry["test"] for t in tests)


def calls_the_gate(entry, script, files, tests):
    """A mutation may pin the CALL SITE rather than the gate: the target is a file the
    gate does not own -- a shared orchestrator, a git hook -- that NAMES the gate's
    script, and the suite it must turn red is one of the gate's own."""
    if entry["target"] in files or not names_suite(entry, tests):
        return False
    path = os.path.join(ROOT, entry["target"])
    return os.path.isfile(path) and mentions(script, _read(path))


def mutation_ids(entries, slug, script, files, tests):
    """An entry is credited to the gate its id prefix names when its target is that
    gate's own script, an imported or shelled-out helper of it, or a call site."""
    return [e["id"] for e in entries if id_slug(e) == slug
            and (e["target"] in files or calls_the_gate(e, script, files, tests))]


def _id_verdict(e, known, owners, files, credited):
    """Why a mutation id credits no gate -- a slug prefix that does not own its target,
    or a non-slug prefix over a file some gate does own -- or None: it credits its gate,
    or its prefix is a descriptive family the allowlist must declare."""
    slug, target = id_slug(e), e["target"]
    names = ", ".join(sorted(s for s, fs in owners.items() if target in fs))
    holds = "owned by %s" % names if names else "owned by no gate"
    if slug in known:
        if target in owners[slug] or e["id"] in credited.get(slug, ()):
            return None
        return "%s does not own %s -- %s" % (slug, target, holds)
    if target in files:
        return "prefix names no preflight slug, and %s is %s" % (target, holds)
    return None


def id_verdicts(table):
    """({frozen key: why it credits no gate}, {family key: id count}): every id is
    credited to the gate its prefix names, off-convention, or in a descriptive family."""
    known = set(known_slugs(_read(PREFLIGHT)))
    owners = {row["slug"]: set(row["own files"]) for row in table}
    credited = {row["slug"]: set(row["mutations"]) for row in table}
    files = {f for fs in owners.values() for f in fs}
    off, families = {}, {}
    for e in mutation_entries():
        why = _id_verdict(e, known, owners, files, credited)
        if why:
            off[ID_FREEZE + e["id"]] = why
        elif id_slug(e) not in known:
            key = FAMILY + id_slug(e)
            families[key] = families.get(key, 0) + 1
    return off, families


def suites():
    """rel -> text for every tests/test-*.sh (the harness is not a suite)."""
    out = {}
    if not os.path.isdir(TESTS_DIR):
        return out
    for fn in sorted(os.listdir(TESTS_DIR)):
        if fn.startswith("test-") and fn.endswith(".sh") and fn != "test-harness.sh":
            path = os.path.join(TESTS_DIR, fn)
            out[os.path.relpath(path, ROOT)] = _read(path)
    return out


def hook_texts():
    """Every versioned git hook, as text. The tier column is a statement about ALL
    of them: reading one path made a second hook's gates report as CI-only."""
    if not os.path.isdir(HOOK_DIR):
        return []
    paths = [os.path.join(HOOK_DIR, fn) for fn in sorted(os.listdir(HOOK_DIR))]
    return [_read(p) for p in paths if os.path.isfile(p)]


def hook_slugs(texts):
    out = set()
    for text in texts:
        m = FAST.search(text)
        if m:
            out |= {s.strip() for s in m.group(1).replace("\\\n", "").split(",") if s.strip()}
    return out


def hook_blocks(text):
    """[(guard variable, body)] for every `if [ -n "${_staged…}" ]` block of the hook."""
    lines, out, i = text.split("\n"), [], 0
    while i < len(lines):
        m = GUARD.match(lines[i])
        i += 1
        if not m:
            continue
        start = i
        while i < len(lines) and lines[i] != "fi":
            i += 1
        out.append((m.group(1), "\n".join(lines[start:i])))
    return out


def hook_scope(needle, text):
    """How ONE hook runs the gate: "scoped" when a staged-files block hands it that
    list (`--changed` is the same list under another name), "relevant" when such a
    block runs it whole-tree, "whole" at the hook's top level, None if unnamed."""
    for var, body in hook_blocks(text):
        if mentions(needle, body):
            return "scoped" if CHANGED in body or mentions(var, body) else "relevant"
    return "whole" if mentions(needle, text) else None


def hook_tier(slug, needle, fast, texts):
    """_FAST_SLUGS runs the whole gate on every commit; any other hook runs it
    unconditionally, whole-tree behind a staged-files `if`, or over that list, and
    the column must say which. The widest scope any hook gives it wins."""
    if slug in fast:
        return "hook+CI"
    scopes = {hook_scope(needle, text) for text in texts}
    for scope, tier in (("whole", "hook (whole tree)+CI"),
                        ("relevant", "hook (whole tree, when relevant)+CI"),
                        ("scoped", "hook (scoped)+CI")):
        if scope in scopes:
            return tier
    return "CI"


def rows():
    text = _read(PREFLIGHT)
    preflight_rel = os.path.relpath(PREFLIGHT, ROOT)
    order = known_slugs(text)
    checks = {c[0]: c for c in run_checks(text)}
    if set(order) != set(checks):
        raise SystemExit("preflight.sh: KNOWN_SLUGS and run_check disagree: %s"
                         % sorted(set(order) ^ set(checks)))
    defs = shell_defs()
    tests = suites()
    entries = mutation_entries()
    hooks = hook_texts()
    fast = hook_slugs(hooks)
    out = []
    for slug in order:
        _s, name, tokens, cmd = checks[slug]
        rel, extent, needle = resolve_script(tokens, cmd, defs, preflight_rel)
        if rel is None:
            raise SystemExit("preflight.sh: no script resolves for slug %s: %s" % (slug, cmd))
        body = script_text(rel, extent)
        files = own_files(rel, body)
        suite_names = [t for t, txt in tests.items() if mentions(needle, txt)]
        row = {
            "slug": slug, "preflight name": name, "script": rel,
            "allow files": allow_files(rel, body),
            "tests": suite_names,
            "mutations": mutation_ids(entries, slug, rel, files, suite_names),
            "hook tier": hook_tier(slug, needle, fast, hooks),
            "own files": files,
        }
        row["proof"] = proof_of(row)
        out.append(row)
    return out


def proof_of(row):
    if row["slug"] in BY_CONSTRUCTION:
        return "by construction"
    kinds = [k for k, col in (("test", "tests"), ("mutation", "mutations")) if row[col]]
    return "+".join(kinds) if kinds else UNPROVEN


def render(table):
    def cell(v):
        if isinstance(v, list):
            v = ", ".join(v)
        return (v or EMPTY).replace("|", "\\|")
    lines = [GENERATED, "# Code quality gate registry", "",
             ("Every `linux/scripts/preflight.sh` slug with its script, allow files, test "
              "suites, mutations and hook tier, derived from the tree; the `gate-registry` "
              "preflight check fails when this table is stale."), "",
             ("Proof rules, in short. Tests: the suite names the needle -- a basename, or "
              "for an inline gate the function on its `run_check` line. Mutations: every id "
              "is `<prefix>.<kebab>`, and the prefix decides. A prefix naming a preflight "
              "slug credits that gate, and its target must be that gate's script or an "
              "imported module beside it. A prefix naming no slug must not target a "
              "registered gate's file at all -- it is a descriptive family over ordinary "
              "build scripts, and the family has to be declared in `gate-proofs.allow`. "
              "Anything else fails until it is renamed, declared or frozen. "
              "Hook tier: the widest scope any versioned hook gives the gate. "
              "`hook+CI` sits in `_FAST_SLUGS` and runs "
              "whole-tree on every commit, `hook (whole tree)+CI` is named at a hook's top "
              "level and runs unconditionally, `hook (whole tree, when relevant)+CI` is run "
              "whole-tree by a block that fires only when the commit touches its inputs, "
              "`hook (scoped)+CI` is run by a hook block "
              "over the staged files alone, `CI` is none of those. Rationale: "
              "docs/code-quality-tooling.md#gate-proof-registry-gate-registry"), "",
             "| " + " | ".join(COLUMNS) + " |",
             "|" + " --- |" * len(COLUMNS)]
    for row in table:
        lines.append("| " + " | ".join(cell(row[c]) for c in COLUMNS) + " |")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="regenerate docs/code-quality-gates.md")
    args = ap.parse_args()
    table = rows()
    text = render(table)
    reg_rel = os.path.relpath(REGISTRY, ROOT)
    print("=== gate registry gate ===")
    if args.write:
        with open(REGISTRY, "w", encoding="utf-8") as fh:
            fh.write(text)
        print("  wrote %s (%d slugs)" % (reg_rel, len(table)))
    unproven = {r["slug"] for r in table if r["proof"] == UNPROVEN}
    frozen = load_keys(ALLOW)
    frozen_ids = {k for k in frozen if k.startswith(ID_FREEZE)}
    frozen_families = {k for k in frozen if k.startswith(FAMILY)}
    off_convention, families = id_verdicts(table)
    print("  %d slugs; %d proven; %d unproven, %d frozen in %s"
          % (len(table), len(table) - len(unproven), len(unproven),
             len(frozen - frozen_ids - frozen_families), os.path.basename(ALLOW)))
    if off_convention or frozen_ids:
        print("  %d mutation id(s) off-convention, %d frozen"
              % (len(off_convention), len(frozen_ids)))
    print("  %d mutation id(s) in %d descriptive famil(ies), %d declared"
          % (sum(families.values()), len(families), len(frozen_families)))
    sys.stdout.flush()
    scripts = {r["slug"]: r["script"] for r in table}
    rc = check_keys(unproven, frozen - frozen_ids - frozen_families,
                    "NEW unproven slug(s) -- write a tests/test-*.sh naming the script, or a "
                    "mutations.json entry targeting it:",
                    "STALE entr(ies) -- the slug is proven now, delete the line "
                    "(the list only ratchets down):",
                    lambda k: "%s  (%s)" % (k, scripts.get(k, "?")))
    rc = check_keys(off_convention, frozen_ids,
                    "mutations.json id(s) pinning a file under a prefix that cannot own it "
                    "-- rename to <owning-slug>.<kebab> so the registry can credit them:",
                    "STALE mutation-id freeze(s) -- the id is renamed or gone, delete the line:",
                    lambda k: "%s  (%s)" % (k, off_convention[k])) or rc
    rc = check_keys(families, frozen_families,
                    "mutations.json id(s) whose prefix is neither a preflight slug nor a declared "
                    "descriptive family -- rename to <owning-slug>.<kebab>, or declare the family:",
                    "STALE mutation-family declaration(s) -- no id carries the prefix any more, "
                    "delete the line:",
                    lambda k: "%s  (%d id(s))" % (k, families[k])) or rc
    current = _read(REGISTRY) if os.path.isfile(REGISTRY) else ""
    if current != text:
        rc = 1
        sys.stderr.write("FAIL: %s is stale -- run: python3 linux/scripts/verify_gate_registry.py --write\n"
                         % reg_rel)
    if rc == 0:
        print("OK: every slug is proven or frozen, and %s is current" % reg_rel)
    return rc


if __name__ == "__main__":
    sys.exit(main())
