#!/usr/bin/env python3
"""Generate website license pages from deps.json + versions.env.

Reads docs/deps/deps.json and linux/scripts/01-core/versions.env (same sources
as third-party-licenses.md) and produces the Flutter asset markdown files that
get rendered at /openSourceLicenses on the website.

Usage:
    python docs/scripts/generate-website-licenses.py --check   # verify files are current
    python docs/scripts/generate-website-licenses.py --write   # regenerate files
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEPS_JSON = REPO_ROOT / "docs/deps/deps.json"
VERSIONS_ENV = REPO_ROOT / "linux/scripts/01-core/versions.env"
ASSETS_DIR = REPO_ROOT / "linux/webserver/license-assets/documents/footer"

EN_TEMPLATE = """# Open Source Licenses

This project's container images bundle several open-source and proprietary
software components.  This page lists the major components, their versions,
repositories, and licenses.

The project's own code is licensed under MIT.  Each upstream component carries
its own license terms.

---

{container_table}

---

## Flutter Web Frontend

The web frontend uses the Flutter SDK and several Dart/Flutter packages.
Their full license texts are bundled in the application at
`/assets/NOTICES` (auto-generated by the Flutter build).
"""

DE_TEMPLATE = """# Open-Source-Lizenzen

Die Container-Images dieses Projekts enthalten mehrere Open-Source- und
proprietäre Softwarekomponenten. Diese Seite listet die wichtigsten
Komponenten, ihre Versionen, Quellen und Lizenzen auf.

Der eigene Code des Projekts steht unter der MIT-Lizenz. Für jede
vorgelagerte Komponente gelten die jeweiligen Lizenzbedingungen.

---

{container_table}

---

## Flutter Web Frontend

Das Web-Frontend verwendet das Flutter SDK und mehrere Dart/Flutter-Pakete.
Die vollständigen Lizenztexte sind in der Anwendung unter
`/assets/NOTICES` gebündelt (automatisch vom Flutter-Build generiert).
"""


def parse_versions_env() -> dict[str, str]:
    result: dict[str, str] = {}
    for line in VERSIONS_ENV.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        result[key.strip()] = value.strip()
    return result


def render_table(versions: dict[str, str]) -> str:
    # Shared renderer (backlog F2, completed 2026-08-10): this script's own
    # copy — which carried the loud-KeyError fix that sync_versions' copy
    # LACKED — was promoted into deps_table.py; both scripts now consume the
    # single source of truth, so the missing-var behavior cannot diverge again.
    from deps_table import render_deps_table_lines

    return "\n".join(render_deps_table_lines(versions))


def generate_content(versions: dict[str, str]) -> tuple[str, str]:
    table = render_table(versions)
    return (
        EN_TEMPLATE.format(container_table=table),
        DE_TEMPLATE.format(container_table=table),
    )


def write_files(en_content: str, de_content: str) -> list[Path]:
    en_path = ASSETS_DIR / "openSourceLicensesEn.md"
    de_path = ASSETS_DIR / "openSourceLicensesDe.md"
    en_path.parent.mkdir(parents=True, exist_ok=True)
    de_path.parent.mkdir(parents=True, exist_ok=True)
    en_path.write_text(en_content, encoding="utf-8")
    de_path.write_text(de_content, encoding="utf-8")
    return [en_path, de_path]


def check_current(en_content: str, de_content: str) -> bool:
    en_path = ASSETS_DIR / "openSourceLicensesEn.md"
    de_path = ASSETS_DIR / "openSourceLicensesDe.md"
    return (
        en_path.exists()
        and en_path.read_text(encoding="utf-8") == en_content
        and de_path.exists()
        and de_path.read_text(encoding="utf-8") == de_content
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate website license pages.")
    parser.add_argument("--check", action="store_true", help="Fail if files are out of date.")
    parser.add_argument("--write", action="store_true", help="Regenerate files in place.")
    return parser.parse_args()


def check_overlay_reaches_the_served_path() -> int:
    """Generating the file is worthless if the image serves a different copy.

    `dist/` ships its own build-time copy of the same licence page, and the
    webserver Dockerfile overlays `license-assets/` on top. Until 2026-08-25 the
    overlay landed one directory too shallow, so the generated file sat at a URL
    the app never requests and the image served a copy last refreshed months
    earlier, missing ~25 components. Nothing caught it: both files existed, both
    were valid Markdown, and only the URL distinguished them.

    Flutter serves declared assets under its own `assets/` root, so an asset
    declared `assets/documents/footer/x.md` is fetched from
    `/assets/assets/documents/footer/x.md`. This asserts the overlay targets
    that layout, and that every licence file the built app carries is covered
    by one the generator owns.
    """
    dockerfile = REPO_ROOT / "linux/webserver/Dockerfile"
    if not dockerfile.exists():
        print(f"Error: {dockerfile} not found", file=sys.stderr)
        return 1

    want = "/var/www/html/assets/assets/"
    copies = [
        line for line in dockerfile.read_text(encoding="utf-8").split("\n")
        if line.startswith("COPY") and "license-assets/" in line
    ]
    if len(copies) != 1:
        print(f"Error: expected exactly one license-assets COPY in {dockerfile.name}, "
              f"found {len(copies)}", file=sys.stderr)
        return 1
    if not copies[0].rstrip().endswith(want):
        print(f"Error: the license overlay must target {want} so it lands on the path the "
              f"built app requests (Flutter nests declared assets under its own assets/ root).\n"
              f"       Found: {copies[0].strip()}", file=sys.stderr)
        return 1

    served = REPO_ROOT / "linux/webserver/dist/assets/assets/documents/footer"
    if served.is_dir():
        generated = {p.name for p in ASSETS_DIR.rglob("openSourceLicenses*.md")}
        shipped = {p.name for p in served.glob("openSourceLicenses*.md")}
        uncovered = shipped - generated
        if uncovered:
            print(f"Error: dist/ ships licence page(s) the generator does not own, so nothing "
                  f"refreshes them: {', '.join(sorted(uncovered))}", file=sys.stderr)
            return 1
    return 0


def main() -> int:
    if not DEPS_JSON.exists():
        print(f"Error: {DEPS_JSON} not found", file=sys.stderr)
        return 1
    if not VERSIONS_ENV.exists():
        print(f"Error: {VERSIONS_ENV} not found", file=sys.stderr)
        return 1

    args = parse_args()

    versions = parse_versions_env()
    en_content, de_content = generate_content(versions)

    # Default is CHECK (matching sync_versions.py): a flagless invocation used
    # to fall through to the WRITE branch and rewrite tracked files.
    if not args.write:
        rc = check_overlay_reaches_the_served_path()
        if check_current(en_content, de_content):
            if rc == 0:
                print("Website license files are up to date, and the image serves them.")
            return rc
        print("Website license files are out of date.", file=sys.stderr)
        print("Run: python docs/scripts/generate-website-licenses.py --write", file=sys.stderr)
        return 1

    # The overlay path is a correctness property of the image, not of the file
    # contents, so --write cannot fix it and must not mask it either.
    rc = check_overlay_reaches_the_served_path()
    paths = write_files(en_content, de_content)
    if rc:
        return rc
    for p in paths:
        print(f"Written: {p.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
