# syntax=docker/dockerfile:1.19

ARG BASE_IMAGE=local/kataglyphis:media
FROM ${BASE_IMAGE}

ARG ENABLE_NVIDIA=false
ARG ENABLE_AMD=false

ARG ANDROID_SDK_VERSION=14742923
ARG ANDROID_NDK_VERSION=29.0.14206865
ARG ANDROID_COMPILE_SDK=36
ARG ANDROID_BUILD_TOOLS=35.0.0
ARG ANDROID_CMAKE_VERSION=4.1.2

SHELL ["bash", "-lc"]

ENV ANDROID_HOME=/opt/android-sdk \
    ANDROID_SDK_ROOT=/opt/android-sdk \
    ANDROID_NDK_HOME=/opt/android-sdk/ndk/${ANDROID_NDK_VERSION} \
    ANDROID_NDK_ROOT=/opt/android-sdk/ndk/${ANDROID_NDK_VERSION}

ENV PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}:${ANDROID_NDK_HOME}:${PATH}"

COPY linux/scripts/setup-android-sdk-ndk.sh /opt/scripts/setup-android-sdk-ndk.sh
RUN chmod +x /opt/scripts/setup-android-sdk-ndk.sh
RUN set -eux; /opt/scripts/setup-android-sdk-ndk.sh

COPY linux/scripts/03-media/gstreamer/android /opt/scripts/media/gstreamer/android
COPY linux/scripts/03-media/onnxruntime/android /opt/scripts/media/onnxruntime/android
COPY linux/scripts/03-media/litert/android /opt/scripts/media/litert/android
COPY linux/scripts/03-media/opencv/android /opt/scripts/media/opencv/android

RUN chmod +x /opt/scripts/media/gstreamer/android/build-android-from-source.sh \
    && chmod +x /opt/scripts/media/gstreamer/android/build-gstreamer.sh \
    && chmod +x /opt/scripts/media/onnxruntime/android/build-android.sh \
    && chmod +x /opt/scripts/media/litert/android/build-android.sh \
    && chmod +x /opt/scripts/media/opencv/android/build-android.sh

RUN set -eux; \
        /opt/scripts/media/gstreamer/android/build-gstreamer.sh

RUN set -eux; \
        /opt/scripts/media/onnxruntime/android/build-android.sh && \
        /opt/scripts/media/litert/android/build-android.sh && \
        /opt/scripts/media/opencv/android/build-android.sh

ENV GSTREAMER_ROOT_ANDROID=/opt/android/gstreamer
ENV ONNXRUNTIME_ROOT_ANDROID=/opt/android/onnxruntime
ENV LITERT_ROOT_ANDROID=/opt/android/litert
ENV OPENCV_ROOT_ANDROID=/opt/android/opencv
